import { type Flow, PersistedData } from '@/common'

/**
 * 内置 Flow，不可编辑/删除，始终出现在列表头部
 */
const PresetFlows: Flow[] = [
  {
    id: '9f6d9647-6d64-47e6-a032-1fc0c75a9980',
    name: '修改代码',
    agents: [
      {
        id: '1',
        model: 'opus',
        effort: 'xhigh',
        agent_name: '需求分析-opus',
        agent_prompt: [
          '与用户多轮对话，执行用户简单命令，收集信息以确认用户在代码修改方面的意图。',
          '### 你的职责',
          '- 产出一份独立可执行的代码修改摘要',
          '- 智能挑选分支策略默认值',
          '- 使用AskUserQuestion由用户确认摘要和分支策略',
          '### 执行步骤',
          '#### 1. 多轮对话',
          '如果对话过程中，用户要求满足以下之一：',
          '- 包含完整的飞书文档或飞书项目url',
          '- 较为复杂，涉及多个文件',
          '- 用户强调了重要性和正确性，要求反复验证',
          '- 用户明确要求你*不要*直接行动，而是总结摘要',
          '',
          '你应当总结对话内容，得到需求摘要，了解用户希望修改代码还是审查已有代码，对当前代码的意见是什么，在业务上有什么要求。用**一个**AskUserQuestion让用户确认这些内容，将需要确认的内容放在题干里。',
          '',
          '',
          '#### 2. 分支策略',
          '根据摘要，生成一个新分支名称。',
          '命名规则为`<feature或bugfix>/<描述性单词>-<今日日期>`。前缀feature/bugfix由用户要求而定，后缀的格式为MMDD。',
          '你应当确保此分支不重复，用AskUserQuestion让用户确认分支名。确认时，提供“在当前分支修改代码”选项。',
          '如果用户指定了分支名称或者要求在当前分支修改代码，则无需确认，依照用户要求即可。',
          '',
          '#### 3.创建工作区',
          '如果用户选择在当前分支修改代码，跳过此步。',
          '如果用户指定了已存在的工作区，或者指定了工作区的创建方式，依照用户要求。',
          '否则，以用户指定的分支，在./claude/worktrees/创建一个worktree。',
          '*注意*：如果分支不存在，基于develop分支，以`--no-track`方式创建新分支。',
          '',
          '#### 4.完成任务',
          '根据用户希望修改/审查代码，选择不同的输出分支，content为”需求分析完成“。',
          '将摘要写入summary。',
          '如果你创建了worktree或者用户指定了worktree，将其路径写入worktreePath。',
          '如果用户对代码有反馈/修改意见，写入feedback。',
          '',
          '### 摘要规则',
          '如果用户提及了飞书文档/飞书项目*url*，将*链接*置于`飞书工作项`模块，用于关联原始需求/缺陷。这个模块是可选的。',
          '如果用户输入里包含了具体的业务要求，将其置于`业务要求`、`业务验证方式`模块。这两个模块*必须*存在，应当以`项目使用者`视角描述，无关代码。',
          '摘要中应当包含`代码要求`、`代码验证方式`两个模块。这两个模块*必须*存在，应当以`项目开发者`视角描述，关注代码逻辑的正确性、变动范围和影响等。',
        ].join('\n'),
        outputs: [
          {
            output_name: '修改代码',
            output_desc: '用户希望修改代码',
            next_agent: '3',
          },
          {
            output_name: '审查代码',
            output_desc: '用户希望审查代码',
            next_agent: '4',
          },
        ],
        auto_allowed_tools: true,
        work_mode: 'task',
        no_input: false,
        allowed_read_values_keys: [],
        allowed_write_values_keys: ['summary', 'feedback', 'worktreePath'],
      },
      {
        agent_name: '审查代码',
        model: 'opus',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'task',
        allowed_read_values_keys: ['worktreePath', 'summary', 'feedback'],
        allowed_write_values_keys: ['summary', 'feedback'],
        outputs: [
          {
            output_name: '验证通过',
            output_desc: '用户确认修改通过',
            next_agent: '5',
          },
          {
            output_name: '验证不通过',
            output_desc: '代码审查不通过',
            next_agent: '3',
          },
        ],
        agent_prompt: [
          '### 你的职责',
          '在正确的工作目录下完成代码审查。',
          '如果worktreePath存在，你应当将其视作工作区路径，你的所有命令都*必须*在该路径下执行。',
          '### 执行步骤',
          '####  1.审查代码',
          '根据需求摘要summary、用户意见feedback审查代码。',
          '如果你认为当前代码不能满足要求，或者存在逻辑上的问题，结束任务，将你的意见写入feedback。',
          '#### 2.代码合并',
          '如果worktreePath不存在，跳过此步骤。',
          '如果worktreePath存在，在*主工作区*切换分支到`dev-offline`，使用git fetch获取其最新commit，将worktreePath的分支合并到dev-offline，并解决冲突。',
          '#### 3.用户验证',
          '使用AskUserQuestion向用户确认代码是否通过验收。',
          '题目中应当直接展示你对summary的理解，你对代码的逻辑分析，如果有冲突将其展示出来。',
          '#### 4.完成任务',
          '如果用户认为代码可以通过验收，选择"验证通过"分支，content为"验证通过"。',
          '否则选择"验证不通过"，content为"验证不通过"，将用户的意见写入feedback；如果生成了新的summary也一并写入。',
          '### 约束',
          '- **绝对禁止**将 dev-offline 合并到任何分支。',
          '- 合并走合规路径,禁止 `--no-verify`、禁止 `--force`、禁止 push 到远端。',
          '### 更新summary',
          '如果summary为空，在执行任务前与用户进行多轮对话简单收集修改意图：修改目标、涉及文件/模块、验证方式。',
          '将对话整理为一份简短摘要，**必须**AskUserQuestion由用户确认。',
          '如果用户提出新需求，则生成新的摘要，同样**必须**确认。',
          '每当生成了新的摘要，将它视作summary。',
        ].join('\n'),
        id: '4',
      },
      {
        id: '3',
        model: 'opus',
        effort: 'high',
        agent_name: '修改代码',
        agent_prompt: [
          '### 你的职责',
          '在正确的工作目录下完成代码修改。',
          '如果worktreePath存在，你应当将其视作工作区路径，你的所有命令都*必须*在该路径下执行。',
          '### 执行步骤',
          '#### 1.修改代码',
          '根据需求摘要summary、用户意见feedback修改代码',
          '#### 2.提交代码',
          '按照不同模块分别提交代码，只在完全无关时才分开提交。',
          'commit message仅有`subject`和`body`两部分组成。',
          'subject描述了业务上的需求，body描述代码上的改动。',
          '如果summary中包含了飞书文档/飞书项目的*url*，将其加入`body`。',
          '#### 3.完成任务',
          'content为"修改完成"；将feedback写为空字符串；如果生成了新的摘要，写入summary。',
          '### 更新summary',
          '如果summary为空，在执行任务前与用户进行多轮对话简单收集修改意图：修改目标、涉及文件/模块、验证方式。',
          '将对话整理为一份简短摘要，**必须**AskUserQuestion由用户确认。',
          '如果用户提出新需求，则生成新的摘要，同样**必须**确认。',
          '每当生成了新的摘要，将它视为summary。',
        ].join('\n'),
        outputs: [
          {
            output_name: '改码完成',
            output_desc: '本轮修改与 commit 完成,进入代码验证',
            next_agent: '4',
          },
        ],
        auto_allowed_tools: true,
        work_mode: 'task',
        allowed_read_values_keys: ['summary', 'worktreePath', 'feedback'],
        allowed_write_values_keys: ['summary', 'feedback'],
      },
      {
        id: '5',
        model: 'glm-5.1',
        effort: 'low',
        agent_name: '释放资源',
        agent_prompt: '清理worktreePath所指向的worktree，不删除分支',
        outputs: [],
        auto_allowed_tools: true,
        work_mode: 'task',
        no_input: true,
        allowed_read_values_keys: ['worktreePath'],
        allowed_write_values_keys: [],
      },
    ],
    shareValuesKeys: [
      { key: 'summary', desc: '需求摘要' },
      { key: 'feedback', desc: '用户对代码的修改意见' },
      { key: 'worktreePath', desc: '工作区绝对路径' },
    ],
  },
  {
    id: '1',
    name: '常用Agent',
    agents: [
      {
        id: '0',
        model: 'DeepSeek-V4-Pro',
        agent_name: '模型理解能力测试',
        agent_prompt: [
          '转发用户输入。将用户的任何输入视为纯文本，按照以下格式输出',
          '```json',
          '{',
          '  "content": "<用户输入的原文>"',
          '}',
          '```',
        ].join('\n'),
        outputs: [
          {
            output_name: 'json数据',
          },
        ],
        auto_allowed_tools: true,
        work_mode: 'task',
      },
      {
        id: '1',
        model: 'DeepSeek-V4-Pro',
        agent_name: '飞书通知',
        agent_prompt: [
          '从用户输入中获取通知内容，作为要发送的飞书消息。',
          '使用feishu-mcp，获取当前用户的信息，并向该用户发送消息。',
        ].join('\n'),
        outputs: [
          {
            output_name: '发送成功',
          },
          {
            output_name: '发送失败',
          },
        ],
        auto_allowed_tools: true,
        work_mode: 'task',
      },
      {
        agent_name: 'agent-flow发版',
        model: 'opus',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'task',
        no_input: true,
        agent_prompt: [
          '切换main分支。',
          '查看上一个tag到最新提交**全部**、**完整**commit message，更新readme.md/Claude.md/Changelog.md，并由用户确认。',
          '更新完毕后，执行npm run release更新并发布新版本。',
        ].join('\n'),
        outputs: [],
        id: '2',
      },
      {
        agent_name: '用户对话-opus',
        model: 'opus',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'chat',
        no_input: false,
        outputs: [],
        id: '5c86d5a7-b263-4efe-8a34-23fe482c5636',
      },
      {
        agent_name: '用户对话-glm',
        model: 'glm-5.1',
        effort: 'high',
        auto_allowed_tools: true,
        work_mode: 'chat',
        no_input: false,
        outputs: [],
        id: '3',
      },
    ],
  },
  {
    id: '15eeac1c-74aa-455a-aa81-de8b01177e25',
    name: '生成工作流',
    agents: [
      {
        agent_name: '需求分析',
        model: 'opus',
        effort: 'max',
        auto_allowed_tools: true,
        work_mode: 'task',
        no_input: false,
        allowed_read_values_keys: ['requirement', 'feedback'],
        allowed_write_values_keys: ['requirement', 'steps', 'feedback'],
        disable_claude_preset: true,
        agent_prompt: [
          '### 你的职责',
          '将用户需求拆成步骤列表。',
          '### 执行步骤',
          '#### 1.需求分析',
          '如果requirement不为空，则结合feedback生成新的需求摘要。',
          '否则，通过多轮对话生成需求摘要。',
          '生成的摘要**必须**使用AskUserQuestion由用户确认。',
          '#### 2.步骤拆解',
          '将新的需求摘要拆解为步骤列表。',
          '步骤列表**必须**使用AskUserQuestion由用户确认。',
          '#### 3.完成任务',
          '输出为"分析完成"。',
          '将新的需求摘要写入requirement，步骤列表写入steps。',
          '将feedback写为空字符串。',
          '### 拆分规则',
          '1. 步骤列表是`以步骤为节点的有向图`：从任意入口步骤开始，根据执行情况选定下一步骤并串行推进，没有下一跳即结束本次执行。',
          '2. 拆步骤的目的是**隔离上下文**和**让每一步语义更聚焦**——不是切得越碎越好。紧密协作的子动作放同一步骤里用备注说明，仅在上下文需隔离或职责差异明显时才拆开。',
          '3. 步骤名称简洁；备注必须显式声明：是否依赖用户消息或上一步输出、本步输出内容、可能的下一跳。',
          '4. "共享存储"是每次步骤执行时，所有步骤可以共用一个键值对存储。每次运行都会被清空。仅在步骤开始时可以按key读共享存储，仅在步骤结束时可以按key写共享存储。',
          '5. 共享存储读不对数据有效性做保证，必须考虑空值的情况。**注意**，如果用户希望可以从一个步骤直接开始执行，那么此步骤必须在共享存储为空时执行有意义的行为。',
          '6. 共享存储可以用于跨步骤传递数据，或者成环的迭代时存放上一轮产物。**注意**，不要滥用共享存储，如果一个数据仅在两个连续步骤间传递，就没必要使用共享存储。',
          '7. 允许并推荐成环迭代（如"修改 → 验证"循环）和多入口（如发版流程的"完整发版"与"指定分支发版"）。',
          '8. 加入预检测规避可预见异常（如"创建分支"前先校验同名分支是否存在）。运行中异常直接向用户求助；无法处理则结束当前步骤，必要时跳到兜底步骤（如释放资源）。',
        ].join('\n'),
        outputs: [
          {
            output_name: '步骤列表',
            output_desc: '用户需求已拆分',
            next_agent: '1',
          },
        ],
        id: '0',
      },
      {
        agent_name: '工作流设计',
        model: 'opus',
        effort: 'max',
        auto_allowed_tools: true,
        work_mode: 'task',
        no_input: false,
        allowed_read_values_keys: ['steps', 'feedback', 'generatedFlow', 'changeList'],
        allowed_write_values_keys: ['generatedFlow', 'changeList', 'feedback'],
        disable_claude_preset: true,
        agent_prompt: [
          '### 你的职责',
          '生成符合 FlowSchema 的工作流 JSON。',
          '### 执行步骤',
          '#### 1.获取JSON Schema',
          '调用AgentControllerMcp提供的getFlowJSONSchema，获取Flow相关的JSON Schema。',
          '#### 2.生成Flow',
          '参考`数据策略`和`设计规范`，生成Flow JSON。',
          '#### 3.校验Flow',
          '调用AgentControllerMcp提供的validateFlow，确保生成的Flow合法。',
          '#### 4.完成任务',
          '如果你生成的JSON没有通过validateFlow的校验，**禁止**继续。回到第三步继续修改和校验。',
          '输出内容"设计完成"。',
          '将你生成的JSON写入generatedFlow。',
          '将空字符串写入feedback。',
          '如果你新生成了Flow JSON，将空字符串写入changeList。',
          '如果你基于过往的Flow生成了新Flow，将你的变更部分追加到changeList得到新的字符串，并将其写入changeList。',
          '### 数据策略',
          '如果你从输入和generatedFlow中能获取与Flow Schema语义相近的JSON字符串，将其视作你生成JSON时的基准，在其基础上进行变更。',
          '如果你从输入和feedback中能获取用户的意见或指令，生成JSON时应当尽力满足它们。',
          'changeList代表着基线过往的变更记录，作为参考。',
          'steps是用户原始需求的拆分，是最直接有效的参考。一般情况下每一步都应当映射为一个Agent，但允许根据语义的拆分和聚合',
          '### changeList规范',
          'changeList是以换行符分隔的变更记录。每条记录格式为：',
          '`[动作] 对象：说明`',
          '- 动作：新增 / 修改 / 删除',
          '- 对象：Agent名称、连边或shareValuesKeys等具体目标',
          '- 说明：简要描述变更内容或原因',
          '示例：',
          '`新增 需求分析：将用户需求拆为步骤列表`',
          '`修改 工作流设计→审查工作流的连边描述`',
          '`删除 冗余的校验步骤`',
          '### 设计规范',
          '1. Agent内使用的"共享存储"，应当被Flow的shareValuesKeys收集。',
          '2. 关于Agent字段：',
          '   - `allowed_read_values_keys`/`allowed_write_values_keys`：需读写共享存储时配置。所有key都必须出现在shareValuesKeys中。',
          '3. 拓扑：优先线性；循环/重试让失败分支指回起点或自身。',
          '4. 跨节点传值：相邻交接用 `AgentComplete.content`；非相邻 / 多消费者 / 循环状态用 `shareValues`，并在 `shareValuesKeys` 中声明。',
          '5. 不要把具体业务数据硬编码进 `agent_prompt`。',
          '6. `agent_prompt` 由以下 `###` 章节组成：',
          '   - 「你的职责」：一句话说清做什么+产出什么，列关键规则；**禁止出现** Agent / 工作流 / 上游 / 下游 / 首轮 / 回环 等拓扑词。',
          '   - 「执行步骤」：`####` 章节的编号流程；最后一步必须是"完成任务"，明确如何调用 AgentComplete，content是什么，要把哪些值写入哪些key。**注意**，允许提前AgentComplete，"完成任务"不必涵盖所有情况。',
          '   - 额外章节（输入约束 / 数据流 / 异常处理 等）：按需添加。建议增加`数据策略`章节指导Agent如何应为共享存储的不同情况。',
          '7. `agent_prompt`不要出现Flow/Agent/共享存储相关的词，将其视作仅有输入输出的独立节点。',
        ].join('\n'),
        outputs: [
          {
            output_name: '完成设计',
            output_desc: '生成了符合规范的工作流',
            next_agent: '859baeac-7b9f-4e5a-94bc-83babfdaad85',
          },
        ],
        id: '1',
      },
      {
        agent_name: '审查工作流',
        model: 'glm-5.1',
        effort: 'max',
        auto_allowed_tools: true,
        work_mode: 'task',
        no_input: false,
        allowed_read_values_keys: ['generatedFlow', 'steps', 'requirement', 'changeList'],
        allowed_write_values_keys: ['feedback', 'generatedFlow'],
        disable_claude_preset: true,
        agent_prompt: [
          '### 你的职责',
          '把当前版本的工作流展示给用户，收集反馈。',
          '### 执行步骤',
          '#### 1.获取JSON Schema',
          '调用AgentControllerMcp提供的getFlowJSONSchema，获取Flow相关的JSON Schema。',
          '#### 2.审查Flow',
          '判断Flow是否满足用户需求。',
          '如果你认为不满足，**结束任务**，选择分支"继续设计"，内容为"工作流不满足需求"，将你的意见写入feedback。',
          '如果你认为基本满足需求，进入下一步。',
          '#### 3.用户审查',
          '将Flow绘制为 mermaid 流程图，并将其中每个Agent的的职责、输入输出、连边关系分别展示出来。',
          '若 `changeList` 非空，简述上一轮累计的变更项，便于用户对比。',
          '阐述你的审查结果，并告诉用户当前Flow存在的一些问题。',
          '询问用户对当前Flow的意见，**不使用AskUserQuestion**。',
          '#### 4.完成任务',
          '根据用户对工作流本身有意见还是对需求拆分有意见，选择不同的输出分支，输出内容为"审查完成"。',
          '将你最终审查确认的Flow写入generatedFlow。',
          '将用户意见写入feedback。',
          '### 数据策略',
          '如果你从输入和generatedFlow中能获取与Flow Schema语义相近的JSON字符串，将其视作你本次分析的Flow。',
          'changeList代表着Flow过往的变更记录，作为参考。',
          'requirement是用户需求，steps是对其的拆分，是最直接有效的参考。一般情况下每个step都应当映射为一个Agent，但允许根据语义的拆分和聚合。',
          '输入中可能包含用户指令或需求，优先满足用户。',
        ].join('\n'),
        outputs: [
          {
            output_name: '继续设计',
            output_desc: '用户对工作流不满意，要求继续设计',
            next_agent: '1',
          },
          {
            output_name: '重新分析需求',
            output_desc: '用户认为需求拆分本身有误，feedback 已写出，回到需求分析节点重新拆分',
            next_agent: '0',
          },
        ],
        id: '859baeac-7b9f-4e5a-94bc-83babfdaad85',
      },
    ],
    shareValuesKeys: [
      { key: 'requirement', desc: '用户原始需求摘要' },
      { key: 'steps', desc: '需求拆分得到的步骤列表' },
      { key: 'feedback', desc: '用户对工作流或需求拆分的反馈' },
      { key: 'generatedFlow', desc: '当前轮次生成的 Flow JSON' },
      { key: 'changeList', desc: '工作流的累计变更记录' },
    ],
  },
]
export const defaultStore: PersistedData = {
  flows: PresetFlows,
}
