import { type Flow, PersistedData } from '@/common'

/**
 * 内置 Flow，不可编辑/删除，始终出现在列表头部
 */
const PresetFlows: Flow[] = [
  {
    id: '9f6d9647-6d64-47e6-a032-1fc0c75a9980',
    name: '修改代码',
    agents: [
      {
        id: '1',
        model: 'opus',
        effort: 'xhigh',
        agent_name: '需求分析',
        is_entry: true,
        agent_prompt: [
          '与用户多轮对话，执行用户简单命令，收集信息以确认用户在代码修改方面的意图。',
          '### 你的职责',
          '- 产出一份独立可执行的代码修改摘要',
          '- 智能挑选分支策略默认值',
          '- 使用AskUserQuestion由用户确认摘要和分支策略',
          '### 执行步骤',
          '#### 1. 多轮对话',
          '如果对话过程中，用户要求满足以下之一：',
          '- 包含完整的飞书文档或飞书项目url',
          '- 较为复杂，涉及多个文件',
          '- 用户强调了重要性和正确性，要求反复验证',
          '- 用户明确要求你*不要*直接行动，而是总结摘要',
          '',
          '你应当总结对话内容，得到需求摘要，了解用户希望修改代码还是审查已有代码，对当前代码的意见是什么，在业务上有什么要求。用**一个**AskUserQuestion让用户确认这些内容，将需要确认的内容放在题干里。',
          '',
          '',
          '#### 2. 分支策略',
          '根据摘要，生成一个新分支名称。',
          '命名规则为`<feature或bugfix>/<描述性单词>-<今日日期>`。前缀feature/bugfix由用户要求而定，后缀的格式为MMDD。',
          '你应当确保此分支不重复，用AskUserQuestion让用户确认分支名。确认时，提供“在当前分支修改代码”选项。',
          '如果用户指定了分支名称或者要求在当前分支修改代码，则无需确认，依照用户要求即可。',
          '',
          '#### 3.创建工作区',
          '如果用户选择在当前分支修改代码，跳过此步。',
          '如果用户指定了已存在的工作区，或者指定了工作区的创建方式，依照用户要求。',
          '否则，以用户指定的分支，在./claude/worktrees/创建一个worktree。',
          '*注意*：如果分支不存在，基于develop分支，以`--no-track`方式创建新分支。',
          '',
          '#### 4.完成任务',
          '根据用户希望修改/审查代码，选择不同的输出分支，content为"需求分析完成"。',
          '如果用户提及了飞书文档/飞书项目*url*，将其写入feishuUrls。',
          '将摘要写入summary。',
          '如果你创建了worktree或者用户指定了worktree，将其路径写入worktreePath。',
          '',
          '### 摘要规则',
          '如果用户输入里包含了具体的业务要求，将其置于`业务要求`、`业务验证方式`模块。这两个模块*必须*存在，应当以`项目使用者`视角描述，无关代码。',
          '摘要中应当包含`代码要求`、`代码验证方式`两个模块。这两个模块*必须*存在，应当以`项目开发者`视角描述，关注代码逻辑的正确性、变动范围和影响等。',
          '如果需求内容较多，应当将其拆分为独立的任务列表，并注明执行顺序、能否并行。',
        ].join('\n'),
        outputs: [
          {
            output_name: '修改代码',
            output_desc: '用户希望修改代码',
            next_agent: '3',
            require_confirm: true,
          },
          {
            output_name: '审查代码',
            output_desc: '用户希望审查代码',
            next_agent: '4',
            require_confirm: true,
          },
        ],
        work_mode: 'task',
        no_input: false,
        allowed_read_values_keys: [],
        allowed_write_values_keys: ['summary', 'worktreePath', 'feishuUrls'],
        deny_tools: ['Bash(git merge)', 'Bash(git push)'],
        must_confirm_tools: ['Edit'],
      },
      {
        id: '3',
        model: 'opus',
        effort: 'high',
        agent_name: '修改代码',
        deny_tools: ['Bash(git merge)', 'Bash(git push)'],
        agent_prompt: [
          '### 你的职责',
          '在正确的工作目录下完成代码修改。',
          '如果worktreePath存在，你应当将其视作工作区路径，你的所有命令都*必须*在该路径下执行。',
          '### 执行步骤',
          '#### 1.修改代码',
          '根据需求摘要和用户意见修改代码。注意，只检查是否符合要求，不处理边界情况，不做代码优化。',
          '如果需求内容较多，应当将其拆分为任务列表，并使用`Workflow`编排subAgent并行执行。',
          '#### 2.提交代码',
          '按照不同模块分别提交代码，只在完全无关时才分开提交。',
          'commit message仅有`subject`和`body`两部分组成。',
          'subject描述了业务上的需求，body描述代码上的改动。',
          '如果feishuUrls存在，将其加入`body`。',
          '#### 3.完成任务',
          '输出你的修改内容。',
        ].join('\n'),
        outputs: [
          {
            output_name: '修改完成',
            output_desc: '本轮修改与 commit 完成',
            next_agent: '4',
          },
        ],
        work_mode: 'silent_task',
        allowed_read_values_keys: ['summary', 'worktreePath', 'feishuUrls'],
      },
      {
        agent_name: '审查代码',
        model: 'opus',
        effort: 'high',
        deny_tools: ['Bash(git merge)', 'Bash(git push)'],
        must_confirm_tools: ['Edit'],
        work_mode: 'task',
        allowed_read_values_keys: ['worktreePath', 'summary'],
        allowed_write_values_keys: ['summary'],
        outputs: [
          {
            output_name: '验证通过',
            require_confirm: true,
            next_agent: '5',
          },
          {
            output_name: '验证不通过',
            output_desc: '代码审查不通过',
            next_agent: '3',
          },
        ],
        agent_prompt: [
          '### 你的职责',
          '在正确的工作目录下完成代码审查。',
          '如果worktreePath存在，你应当将其视作工作区路径，你的所有命令都*必须*在该路径下执行。',
          '### 执行步骤',
          '####  1.审查代码',
          '根据需求摘要summary和用户意见审查代码。注意，只检查是否符合需求，忽略优化和安全问题。',
          '如果需求内容较多，应当将其拆分为任务列表，并使用`Workflow`编排subAgent并行执行。',
          '如果你认为当前代码不能满足要求，或者存在逻辑上的问题，调用CompleteTask，输出分支选择"验证不通过"，content为你的意见。',
          '否则，进入下一步',
          '#### 2.完成任务',
          '调用CompleteTask，输出分支选择"验证通过"，content为你的分析结果。',
          '本次调用会受用户审阅，用户可能提出质询，和用户充分讨论代码变更。',
          '如果用户最终认为验证不通过，调用CompleteTask，输出分支选择"验证不通过"。',
          '注意，如果需求变动，写入新的summary。确保summary已被确认。',
          '如果用户认为验证通过，再次调用CompleteTask，分支"验证通过"。',
        ].join('\n'),
        id: '4',
      },
      {
        node_type: 'code',
        agent_name: '释放资源',
        agent_desc: '移除worktree',
        no_input: true,
        code: "if(values.worktreePath){\n  await runCommand(`git worktree remove -f ${values.worktreePath}`)\n  return { content: 'worktree已移除' }\n}\n\nreturn { content: '没有worktree' }",
        outputs: [],
        id: '5',
      },
    ],
    shareValuesKeys: [
      { key: 'summary', desc: '需求摘要' },
      { key: 'worktreePath', desc: '工作区绝对路径' },
      { key: 'feishuUrls', desc: '飞书工作项的链接' },
    ],
  },
  {
    id: '1',
    name: '常用Agent',
    agents: [
      {
        agent_name: 'agent-flow发版',
        model: 'sonnet[1m]',
        effort: 'high',
        work_mode: 'task',
        no_input: true,
        agent_prompt: [
          '切换main分支。',
          '查看上一个tag到最新提交**全部**、**完整**commit message，更新readme.md/Claude.md/Changelog.md，并由用户确认。',
          'Changelog.md只保留最新版本；当归档文件（changelogs/目录下）累积到10个版本时，新建下一个归档文件，命名格式为v起始版本-v结束版本.md（如v0.0.38-v0.0.47.md）。',
          '更新完毕后，执行npm run release更新并发布新版本。',
        ].join('\n'),
        outputs: [],
        id: '2',
      },
      {
        agent_name: '用户对话-qwen',
        model: 'qwen3.7-max',
        effort: 'high',
        work_mode: 'chat',
        no_input: false,
        outputs: [],
        id: '0',
      },
      {
        agent_name: '用户对话-sonnet',
        model: 'sonnet[1m]',
        effort: 'high',
        work_mode: 'chat',
        no_input: false,
        outputs: [],
        id: '1',
      },
      {
        agent_name: '用户对话-opus',
        model: 'opus',
        effort: 'high',
        work_mode: 'chat',
        no_input: false,
        outputs: [],
        id: '5c86d5a7-b263-4efe-8a34-23fe482c5636',
      },
      {
        agent_name: '用户对话-opus-max',
        model: 'opus',
        effort: 'max',
        work_mode: 'chat',
        no_input: false,
        outputs: [],
        id: '5',
      },
      {
        agent_name: '用户对话-glm',
        model: 'glm-5.1',
        effort: 'max',
        work_mode: 'chat',
        no_input: false,
        outputs: [],
        id: '4',
      },
    ],
  },
  {
    id: '15eeac1c-74aa-455a-aa81-de8b01177e25',
    name: '生成工作流',
    agents: [
      {
        agent_name: '需求分析',
        model: 'opus',
        effort: 'max',
        work_mode: 'task',
        no_input: false,
        is_entry: true,
        allowed_write_values_keys: ['requirement', 'steps'],
        deny_tools: ['Bash(git merge)', 'Bash(git push)', 'Edit'],
        isolation_mode: true,
        agent_prompt: [
          '### 你的职责',
          '将用户需求拆成步骤列表。',
          '### 执行步骤',
          '#### 1.需求分析',
          '通过多轮对话生成需求摘要，由用户确认。',
          '#### 2.步骤拆解',
          '将新的需求摘要拆解为步骤列表，由用户确认。',
          '#### 3.完成任务',
          '输出为"分析完成"。',
          '将新的需求摘要写入requirement，步骤列表写入steps。',
          '### 拆分规则',
          '1. 步骤列表是`以步骤为节点的有向图`：从任意入口步骤开始，根据执行情况选定下一步骤并串行推进，没有下一跳即结束本次执行。',
          '2. 拆步骤的目的是**隔离上下文**和**让每一步语义更聚焦**——不是切得越碎越好。紧密协作的子动作放同一步骤里用备注说明，仅在上下文需隔离或职责差异明显时才拆开。',
          '3. 步骤名称简洁；备注必须显式声明：是否依赖用户消息或上一步输出、本步输出内容、可能的下一跳。',
          '4. "共享存储"是每次步骤执行时，所有步骤可以共用一个键值对存储。每次运行都会被清空。仅在步骤开始时可以按key读共享存储，仅在步骤结束时可以按key写共享存储。',
          '5. 共享存储读不对数据有效性做保证，必须考虑空值的情况。**注意**，如果用户希望可以从一个步骤直接开始执行，那么此步骤必须在共享存储为空时执行有意义的行为。',
          '6. 共享存储可以用于跨步骤传递数据，或者成环的迭代时存放上一轮产物。**注意**，不要滥用共享存储，如果一个数据仅在两个连续步骤间传递，就没必要使用共享存储。',
          '7. 允许并推荐成环迭代（如"修改 → 验证"循环）和多入口（如发版流程的"完整发版"与"指定分支发版"）。',
          '8. 加入预检测规避可预见异常（如"创建分支"前先校验同名分支是否存在）。运行中异常直接向用户求助；无法处理则结束当前步骤，必要时跳到兜底步骤（如释放资源）。',
        ].join('\n'),
        outputs: [
          {
            output_name: '分析完毕',
            next_agent: '1',
            require_confirm: true,
          },
        ],
        id: '0',
      },
      {
        agent_name: '工作流设计',
        model: 'opus',
        effort: 'max',
        work_mode: 'silent_task',
        no_input: false,
        allowed_read_values_keys: ['steps', 'generatedFlow', 'changeList'],
        allowed_write_values_keys: ['generatedFlow', 'changeList'],
        deny_tools: ['Bash(git merge)', 'Bash(git push)', 'Edit'],
        isolation_mode: true,
        agent_prompt: [
          '### 你的职责',
          '生成符合 FlowSchema 的工作流 JSON。',
          '### 执行步骤',
          '#### 1.获取JSON Schema',
          '调用GetFlowJSONSchema。',
          '#### 2.生成Flow',
          '参考`数据策略`和`设计规范`，生成Flow JSON。',
          '#### 3.校验Flow',
          '调用ValidateFlow，确保生成的Flow合法。',
          '#### 4.完成任务',
          '任务完成后，输出内容"设计完成"。',
          '将你生成的JSON写入generatedFlow。',
          '将空字符串写入feedback。',
          '如果你新生成了Flow JSON，将空字符串写入changeList。',
          '如果你基于过往的Flow生成了新Flow，将你的变更部分追加到changeList得到新的字符串，并将其写入changeList。',
          '### 数据策略',
          '如果你从输入和generatedFlow中能获取与Flow Schema语义相近的JSON字符串，将其视作你生成JSON时的基准，在其基础上进行变更。',
          '如果你从输入和feedback中能获取用户的意见或指令，生成JSON时应当尽力满足它们。',
          'changeList代表着基线过往的变更记录，作为参考。',
          'steps是用户原始需求的拆分，是最直接有效的参考。一般情况下每一步都应当映射为一个Agent，但允许根据语义的拆分和聚合',
          '### changeList规范',
          'changeList是以换行符分隔的变更记录。每条记录格式为：',
          '`[动作] 对象：说明`',
          '- 动作：新增 / 修改 / 删除',
          '- 对象：Agent名称、连边或shareValuesKeys等具体目标',
          '- 说明：简要描述变更内容或原因',
          '### 设计规范',
          '1. Agent内使用的"共享存储"，应当被Flow的shareValuesKeys收集。',
          '2. 关于Agent字段：',
          '   - `allowed_read_values_keys`/`allowed_write_values_keys`：需读写共享存储时配置。所有key都必须出现在shareValuesKeys中。',
          '3. **不**考虑极端情况导致的执行错误，不需要兜底。',
          '4. 跨节点传值：相邻交接，前驱直接"将xxx作为输出"；非相邻 / 多消费者 / 循环状态用 `shareValues`，并在 `shareValuesKeys` 中声明。',
          '5. 不要把具体业务数据硬编码进 `agent_prompt`。',
          '6. `agent_prompt` 由以下 `###` 章节组成：',
          '   - 「你的职责」：一句话说清做什么+产出什么，列关键规则；**禁止出现** Agent / 工作流 / 上游 / 下游 / 首轮 / 回环 等拓扑词。',
          '   - 「执行步骤」：`####` 章节的编号流程；最后一步必须是"完成任务"，明确如何调用 CompleteTask，content是什么，要把哪些值写入哪些key。**注意**，允许提前CompleteTask，"完成任务"不必涵盖所有情况。',
          '   - 额外章节（输入约束 / 数据流 等）：按需添加。建议增加`数据策略`章节指导Agent如何应为共享存储的不同情况。',
          '7. `agent_prompt`不要出现Flow/Agent/共享存储相关的词，将其视作仅有输入输出的独立节点。',
        ].join('\n'),
        outputs: [
          {
            output_name: '设计完毕',
            next_agent: '859baeac-7b9f-4e5a-94bc-83babfdaad85',
          },
        ],
        id: '1',
      },
      {
        agent_name: '审查工作流',
        model: 'glm-5.1',
        effort: 'max',
        work_mode: 'silent_task',
        no_input: false,
        allowed_read_values_keys: ['generatedFlow', 'steps', 'requirement', 'changeList'],
        deny_tools: ['Bash(git merge)', 'Bash(git push)', 'Edit'],
        isolation_mode: true,
        agent_prompt: [
          '### 你的职责',
          '审查Flow是否符合需求以及可能存在的问题。',
          '### 执行步骤',
          '#### 1.获取JSON Schema',
          '调用GetFlowJSONSchema',
          '#### 2.初步验证',
          '判断Flow是否满足用户需求。',
          '注意，只验证逻辑的正确性，确保正确使用Flow时不会出错，确保shareValues能被正确使用，忽略边界情况和安全性问题。',
          '如果不满足，调用CompleteTask，选择分支"验证失败"，输出你的意见。',
          '否则，进入下一步。',
          '#### 3.深度审查',
          '将Flow绘制为 mermaid 流程图，并将其中每个Agent的的职责、输入输出、连边关系分别展示出来，说明节点如何使用和修改shareValues。',
          '若 `changeList` 非空，简述上一轮累计的变更项。',
          '#### 4.完成任务',
          '调用CompleteTask，选择分支"验证通过"，content为"审查通过"。',
          '注意，**不要**修改content内容。',
          '### 数据策略',
          '如果你从输入和generatedFlow中能获取与Flow Schema语义相近的JSON字符串，将其视作你本次分析的Flow。',
          'changeList代表着Flow过往的变更记录，作为参考。',
          'requirement是用户需求，steps是对其的拆分，是最直接有效的参考。一般情况下每个step都应当映射为一个Agent，但允许根据语义的拆分和聚合。',
        ].join('\n'),
        outputs: [
          {
            output_name: '验证失败',
            next_agent: '1',
          },
          {
            output_name: '验证通过',
            require_confirm: true,
          },
        ],
        id: '859baeac-7b9f-4e5a-94bc-83babfdaad85',
      },
    ],
    shareValuesKeys: [
      { key: 'requirement', desc: '用户原始需求摘要' },
      { key: 'steps', desc: '需求拆分得到的步骤列表' },
      { key: 'generatedFlow', desc: '当前轮次生成的 Flow JSON' },
      { key: 'changeList', desc: '工作流的累计变更记录' },
    ],
  },
]
export const defaultStore: PersistedData = {
  flows: PresetFlows,
}
