import { Flow } from '.'

export const PresetFlows: Flow[] = [
  {
    id: '1',
    name: '修改代码',
    agents: [
      {
        id: '0',
        node_type: 'code',
        agent_name: '在worktree处理需求',
        agent_desc: '创建随机分支和worktree，设置工作目录',
        is_entry: true,
        outputs: [{ output_name: '准备完成', next_agent: '1' }],
        code: [
          'const suffix = Math.random().toString(36).slice(2, 10)',
          'const branchName = `agent-flow-dev/${suffix}`',
          'const worktreePath = `.claude/worktrees/${suffix}`',
          'await runCommand(`git worktree add --no-track -b ${branchName} ${worktreePath}`)',
          'const absPath = (await runCommand(`git -C ${worktreePath} rev-parse --show-toplevel`)).trim()',
          'return {',
          "  output_name: '准备完成',",
          '  content: input,',
          '  cwd: absPath',
          '}',
        ].join('\n'),
      },
      {
        id: '1',
        model: 'sonnet[1m]',
        effort: 'high',
        agent_name: '需求分析',
        node_type: 'agent',
        is_entry: true,
        agent_prompt: [
          '### 你的职责',
          '总结用户需求，仅做**只读**规划',
          '### 执行步骤',
          '#### 1. 需求分析',
          '分析用户需求，查看实现情况',
          '如果需求未实现，总结或更新需求',
          '#### 2.完成任务',
          '如果需求已经实现，调用mcp__AgentControllerMcp__CompleteTask，分支"需求已实现"',
          '否则，选择分支"分析完成"，如果总结或更新了需求，将其写入requirement',
          '### 摘要规则',
          '如果用户输入里包含了具体的业务要求，将其置于`业务要求`、`业务验证方式`模块这两个模块*必须*存在，应当以`项目使用者`视角描述，无关代码',
          '摘要中应当包含`代码要求`、`代码验证方式`两个模块这两个模块*必须*存在，应当以`项目开发者`视角描述，关注代码逻辑的正确性、变动范围和影响等',
          '如果需求内容较多，应当将其拆分为独立的任务列表，并注明执行顺序、能否并行',
          '### 分支规则',
          '如果你处于主工作区，忽略此规则',
          '仅在你不处于主工作区且分支"需求已实现"时，根据需求生成分支名称，并写入branchName，确保新名称不重复',
          '只生成分支名，**不创建新分支，不修改已有的分支名称**',
        ].join('\n'),
        outputs: [
          {
            output_name: '分析完成',
            output_desc: '将用户需求总结为摘要',
            next_agent: '2',
            require_confirm: true,
          },
          {
            output_name: '需求已实现',
            output_desc: '用户需求已经实现',
            next_agent: '3',
            require_confirm: true,
          },
        ],
        work_mode: 'task',
        allowed_read_values_keys: ['requirement'],
        allowed_write_values_keys: ['requirement', 'branchName'],
        deny_tools: ['Bash(git commit)', 'Bash(git merge)', 'Bash(git push)', 'Edit'],
      },
      {
        id: '2',
        model: 'qwen3.7-max',
        node_type: 'agent',
        effort: 'high',
        agent_name: '修改代码',
        deny_tools: ['Bash(git merge)', 'Bash(git push)'],
        plan_mode: true,
        agent_prompt: [
          '### 你的职责',
          '根据需求摘要修改代码',
          '### 执行步骤',
          '#### 1.修改代码',
          '根据需求摘要和用户意见修改代码注意，只检查是否符合要求，不处理边界情况，不做代码优化',
          '如果需求内容较多，应当将其拆分为任务列表，并使用`Workflow`编排subAgent并行执行',
          '#### 2.提交代码',
          '按照不同模块分别提交代码，只在完全无关时才分开提交',
          'commit message仅有`subject`和`body`两部分组成',
          'subject描述了业务上的需求，body描述代码上的改动',
          '#### 3.完成任务',
          '输出你的修改内容',
        ].join('\n'),
        outputs: [
          {
            output_name: '修改完成',
            next_agent: '1',
          },
        ],
        work_mode: 'silent_task',
        allowed_read_values_keys: ['requirement'],
      },
      {
        node_type: 'code',
        agent_name: '收尾工作',
        agent_desc: '分支重命名，移除worktree',
        no_input: true,
        code: [
          'if(!cwd) return { content: `主工作区代码修改已完成` }',
          '// 重命名分支',
          'const branchName = values.branchName',
          'if (branchName) {',
          '  await runCommand(`git -C "${cwd}" branch -m ${branchName}`)',
          '}',
          '// 清理worktree',
          'await runCommand(`git worktree remove -f "${cwd}"`)',
          'return { content: `分支: ${branchName}  \\n代码修改已完成` }',
        ].join('\n'),
        id: '3',
      },
    ],
    shareValuesKeys: [
      { key: 'requirement', desc: '需求摘要' },
      { key: 'branchName', desc: '当前工作分支名' },
    ],
  },
  {
    id: '2',
    name: '执行复杂任务',
    agents: [
      {
        is_entry: true,
        no_output: true,
        node_type: 'agent',
        agent_name: '需求分析',
        effort: 'xhigh',
        agent_desc: '分析用户需求，拆分为有序子任务列表',
        model: 'opus',
        deny_tools: ['Bash(git push)', 'Bash(git commit)', 'Bash(git merge)', 'Edit'],
        work_mode: 'task',
        allowed_read_values_keys: ['requirement', 'remark'],
        allowed_write_values_keys: ['tasks', 'remark', 'requirement'],
        outputs: [
          {
            output_name: '分析完成',
            output_desc: '分析用户需求，用子任务列表的方式描述实现需求的方式',
            require_confirm: true,
            next_agent: '2',
          },
          {
            output_name: '需求已实现',
            output_desc: '当前状况已满足用户需求，无需更改',
            require_confirm: true,
          },
        ],
        agent_prompt: [
          '### 你的职责',
          '分析用户需求，判断完成情况如果没有完成，生成子任务列表',
          '仅做**只读**规划，不要修改文件',
          '### 执行步骤',
          '#### 1. 需求分析与拆分',
          '根据requirement和用户输入，分析用户需求',
          '如果需求尚未实现，思考实现方式，并生成子任务列表',
          '#### 2. 完成任务',
          '调用 mcp__AgentControllerMcp__CompleteTask',
          '如果需求已实现，选择分支"需求已实现"',
          '如果需求未实现，选择分支"分析完成",将你分析得到的用户需求写入requirement，将子任务列表写入tasks如果存在所有任务执行时共用的注意事项，将其写入remark，部分任务的注意事项只写入任务体',
          '如果用户质询你的结论，与用户讨论得到最终结论后，按照上述规则再次调用mcp__AgentControllerMcp__CompleteTask',
          '### 子任务列表规范',
          '**必须**设计任务列表，**不要**执行',
          '子任务列表由串行的子任务构成，逐个执行可以实现用户需求在变更较少时，列表中允许只有一个子任务',
          '每个子任务由背景、具体执行方式、验证方式组成，并按照模块、语义、涉及范围划分，大小适中',
          '子任务执行时无法感知其他子任务和需求，因此每个子任务应当尽可能详细，包含执行任务所需的所有信息',
          '写入子任务列表时，格式应当是**字符串数组**，且是**合法JSON**',
        ].join('\n'),
        id: '1',
      },
      {
        node_type: 'code',
        agent_name: '初始化',
        no_input: true,
        outputs: [
          {
            output_name: '初始化完成',
            next_agent: '4',
          },
          {
            output_name: '格式错误',
            next_agent: '3',
          },
        ],
        code: [
          'try {',
          '  const parsed = JSON.parse(values.tasks)',
          "  if(!Array.isArray(parsed) || parsed.some(v => typeof v !== 'string')){",
          "    throw new Error('')",
          '  }',
          '  return {',
          "    output_name:'初始化完成',",
          "    values: { tasks: JSON.stringify(parsed, null, 2), next: '0'}",
          '  }',
          '} catch{',
          '  return {',
          "    output_name: '格式错误'",
          '  }',
          '}',
        ].join('\n'),
        id: '2',
      },
      {
        node_type: 'agent',
        agent_name: '规范数据格式',
        agent_desc: '将子任务列表转化为合法的字符串数组JSON',
        model: 'glm-5.1',
        effort: 'high',
        work_mode: 'silent_task',
        no_input: true,
        no_output: true,
        isolation_mode: true,
        allowed_read_values_keys: ['tasks'],
        allowed_write_values_keys: ['tasks'],
        deny_tools: ['Bash(git merge)', 'Bash(git commit)', 'Bash(git push)', 'Edit'],
        outputs: [
          {
            output_name: '格式已处理',
            next_agent: '2',
          },
        ],
        agent_prompt: [
          '### 你的职责',
          '将子任务列表规范化，转化为合法JSON字符串',
          '### 执行步骤',
          '#### 1. 转化JSON',
          '根据tasks的语义，生成JSON字符串数组数组中的每一项与子任务一一对应',
          '如果没有子任务，可以写入空数组',
          '**保留task的完整内容，禁止修改，禁止执行，只读**',
          '#### 2. 完成任务',
          '调用 mcp__AgentControllerMcp__CompleteTask，将子任务列表JSON写入tasks注意，写入值必须是**合法的JSON字符串**，必须是**字符串数组**',
        ].join('\n'),
        id: '3',
      },
      {
        node_type: 'code',
        agent_name: '子任务调度',
        no_input: true,
        outputs: [
          {
            output_name: '执行子任务',
            next_agent: '5',
          },
          {
            output_name: '验证需求',
            next_agent: '1',
          },
        ],
        code: [
          'const next = parseInt(values.next)',
          'const tasks = JSON.parse(values.tasks)',
          'if(next === tasks.length || tasks.length === 0){',
          '  return {',
          "    output_name: '验证需求',",
          '  }',
          '}',
          'const current_task = tasks[next>=0 && next<tasks.length ? next: 0]',
          'return {',
          "  content: '执行任务',",
          "  output_name: '执行子任务',",
          '  values: { current_task, next: `${next + 1}` }',
          '}',
        ].join('\n'),
        id: '4',
      },
      {
        node_type: 'agent',
        agent_name: '任务执行',
        agent_desc: '执行当前任务描述，输出执行结果',
        model: 'qwen3.7-max',
        work_mode: 'silent_task',
        effort: 'high',
        plan_mode: true,
        deny_tools: ['Bash(git merge)', 'Bash(git push)'],
        allowed_read_values_keys: ['current_task', 'remark'],
        outputs: [
          {
            output_name: '执行完成',
            next_agent: '6',
          },
        ],
        agent_prompt: [
          '### 你的职责',
          '完成**current_task**描述的任务',
          '### 执行步骤',
          '#### 1. 执行任务',
          '参考输入，遵守remark，执行current_task',
          '#### 2. 完成任务',
          '调用 mcp__AgentControllerMcp__CompleteTask，content 为详细的执行报告',
        ].join('\n'),
        id: '5',
      },
      {
        node_type: 'agent',
        agent_name: '结果验证',
        agent_desc: '验证执行结果是否满足任务要求',
        model: 'glm-5.1',
        effort: 'high',
        work_mode: 'silent_task',
        deny_tools: ['Bash(git merge)', 'Bash(git commit)', 'Bash(git push)', 'Edit'],
        allowed_read_values_keys: ['current_task', 'remark'],
        outputs: [
          {
            output_name: '验证通过',
            next_agent: '4',
          },
          {
            output_name: '验证不通过',
            next_agent: '5',
          },
        ],
        agent_prompt: [
          '### 你的职责',
          '根据**current_task**和remark，验证执行结果',
          '仅做**只读**验证，**禁止修改文件**',
          '### 执行步骤',
          '#### 1. 验证结果',
          '参考输入，验证current_task是否被完成，且遵守remark',
          '#### 2. 完成任务',
          '调用 mcp__AgentControllerMcp__CompleteTask，根据验证结果选择对应分支，content 为详细的验证报告',
        ].join('\n'),
        id: '6',
      },
    ],
    shareValuesKeys: [
      {
        key: 'tasks',
        desc: '由需求拆分得到的子任务列表',
      },
      {
        key: 'next',
        desc: '下一个子任务下标',
      },
      {
        key: 'current_task',
        desc: '任务描述',
      },
      {
        key: 'requirement',
        desc: '用户的原始需求',
      },
      {
        key: 'remark',
        desc: '任务执行的注意事项',
      },
    ],
  },
  {
    id: '3',
    name: '常用Agent',
    agents: [
      {
        node_type: 'agent',
        agent_name: '用户对话-qwen',
        model: 'qwen3.7-max',
        effort: 'high',
        work_mode: 'chat',
        id: '1',
      },
      {
        node_type: 'agent',
        agent_name: '用户对话-sonnet',
        model: 'sonnet[1m]',
        effort: 'high',
        work_mode: 'chat',
        id: '2',
      },
      {
        node_type: 'agent',
        agent_name: '用户对话-opus',
        model: 'opus',
        effort: 'high',
        work_mode: 'chat',
        id: '3',
      },
      {
        node_type: 'agent',
        agent_name: '用户对话-opus-max',
        model: 'opus',
        effort: 'max',
        work_mode: 'chat',
        id: '4',
      },
      {
        node_type: 'agent',
        agent_name: '用户对话-glm',
        model: 'glm-5.1',
        effort: 'max',
        work_mode: 'chat',
        id: '5',
      },
      {
        node_type: 'agent',
        agent_name: 'agent-flow发版',
        model: 'sonnet[1m]',
        effort: 'high',
        work_mode: 'silent_task',
        no_output: true,
        plan_mode: true,
        agent_prompt: [
          '如果当前在main分支，stash工作区变更',
          '如果当前不在main分支，基于main创建worktree，后续命令在工作区执行',
          '查看main分支上一个tag到最新提交**全部**、**完整**commit message，更新README.md/CLAUDE.md/CHANGELOG.md',
          'Changelog.md只保留最新版本；当归档文件（changelogs/目录下）累积到10个版本时，新建下一个归档文件，命名格式为v起始版本-v结束版本.md（如v0.0.38-v0.0.47.md）',
        ].join('\n'),
        id: '0',
        outputs: [{ output_name: '文档更新完毕', next_agent: '6' }],
      },
      {
        id: '6',
        agent_name: '发版',
        node_type: 'code',
        code: "return { content: await runCommand('npm run release') }",
        no_input: true,
      },
    ],
  },
  {
    id: '4',
    name: '生成工作流',
    agents: [
      {
        node_type: 'agent',
        agent_name: '需求分析',
        model: 'opus',
        effort: 'max',
        work_mode: 'task',
        is_entry: true,
        allowed_write_values_keys: ['requirement', 'steps'],
        deny_tools: ['Bash(git commit)', 'Bash(git merge)', 'Bash(git push)', 'Edit'],
        isolation_mode: true,
        no_output: true,
        agent_prompt: [
          '### 你的职责',
          '将用户需求拆成步骤列表',
          '### 执行步骤',
          '#### 1.需求分析',
          '通过多轮对话生成需求摘要，由用户确认',
          '#### 2.步骤拆解',
          '将新的需求摘要拆解为步骤列表，由用户确认',
          '#### 3.完成任务',
          '将新的需求摘要写入requirement，步骤列表写入steps',
          '### 拆分规则',
          '1. 步骤列表是`以步骤为节点的有向图`：从任意入口步骤开始，根据执行情况选定下一步骤并串行推进，没有下一跳即结束本次执行',
          '2. 拆步骤的目的是**隔离上下文**和**让每一步语义更聚焦**——不是切得越碎越好紧密协作的子动作放同一步骤里用备注说明，仅在上下文需隔离或职责差异明显时才拆开',
          '3. 步骤名称简洁；备注必须显式声明：是否依赖用户消息或上一步输出、本步输出内容、可能的下一跳',
          '4. "共享存储"是每次步骤执行时，所有步骤可以共用一个键值对存储每次运行都会被清空仅在步骤开始时可以按key读共享存储，仅在步骤结束时可以按key写共享存储',
          '5. 共享存储读不对数据有效性做保证，必须考虑空值的情况**注意**，如果用户希望可以从一个步骤直接开始执行，那么此步骤必须在共享存储为空时执行有意义的行为',
          '6. 共享存储可以用于跨步骤传递数据，或者成环的迭代时存放上一轮产物**注意**，不要滥用共享存储，如果一个数据仅在两个连续步骤间传递，就没必要使用共享存储',
          '7. 允许并推荐成环迭代（如"修改 → 验证"循环）和多入口（如发版流程的"完整发版"与"指定分支发版"）',
          '8. 加入预检测规避可预见异常（如"创建分支"前先校验同名分支是否存在）运行中异常直接向用户求助；无法处理则结束当前步骤，必要时跳到兜底步骤（如释放资源）',
        ].join('\n'),
        outputs: [
          {
            output_name: '分析完毕',
            next_agent: '2',
            require_confirm: true,
          },
        ],
        id: '1',
      },
      {
        node_type: 'agent',
        agent_name: '工作流设计',
        model: 'opus',
        effort: 'max',
        work_mode: 'silent_task',
        allowed_read_values_keys: ['steps', 'generatedFlow', 'changeList'],
        allowed_write_values_keys: ['generatedFlow', 'changeList'],
        deny_tools: ['Bash(git commit)', 'Bash(git merge)', 'Bash(git push)', 'Edit'],
        isolation_mode: true,
        agent_prompt: [
          '### 你的职责',
          '生成符合 FlowSchema 的工作流 JSON',
          '### 执行步骤',
          '#### 1.获取JSON Schema',
          '调用GetFlowJSONSchema',
          '#### 2.生成Flow',
          '参考`数据策略`和`设计规范`，生成Flow JSON',
          '#### 3.校验Flow',
          '调用ValidateFlow，确保生成的Flow合法',
          '#### 4.完成任务',
          '任务完成后，输出内容"设计完成"',
          '将你生成的JSON写入generatedFlow',
          '将空字符串写入feedback',
          '如果你新生成了Flow JSON，将空字符串写入changeList',
          '如果你基于过往的Flow生成了新Flow，将你的变更部分追加到changeList得到新的字符串，并将其写入changeList',
          '### 数据策略',
          '如果你从输入和generatedFlow中能获取与Flow Schema语义相近的JSON字符串，将其视作你生成JSON时的基准，在其基础上进行变更',
          '如果你从输入和feedback中能获取用户的意见或指令，生成JSON时应当尽力满足它们',
          'changeList代表着基线过往的变更记录，作为参考',
          'steps是用户原始需求的拆分，是最直接有效的参考一般情况下每一步都应当映射为一个Agent，但允许根据语义的拆分和聚合',
          '### changeList规范',
          'changeList是以换行符分隔的变更记录每条记录格式为：',
          '`[动作] 对象：说明`',
          '- 动作：新增 / 修改 / 删除',
          '- 对象：Agent名称、连边或shareValuesKeys等具体目标',
          '- 说明：简要描述变更内容或原因',
          '### 设计规范',
          '1. Agent内使用的"共享存储"，应当被Flow的shareValuesKeys收集',
          '2. 关于Agent字段：',
          '   - `allowed_read_values_keys`/`allowed_write_values_keys`：需读写共享存储时配置所有key都必须出现在shareValuesKeys中',
          '3. **不**考虑极端情况导致的执行错误，不需要兜底',
          '4. 跨节点传值：相邻交接，前驱直接"将xxx作为输出"；非相邻 / 多消费者 / 循环状态用 `shareValues`，并在 `shareValuesKeys` 中声明',
          '5. 不要把具体业务数据硬编码进 `agent_prompt`',
          '6. `agent_prompt` 由以下 `###` 章节组成：',
          '   - 「你的职责」：一句话说清做什么+产出什么，列关键规则；**禁止出现** Agent / 工作流 / 上游 / 下游 / 首轮 / 回环 等拓扑词',
          '   - 「执行步骤」：`####` 章节的编号流程；最后一步必须是"完成任务"，明确如何调用 mcp__AgentControllerMcp__CompleteTask，content是什么，要把哪些值写入哪些key**注意**，允许提前mcp__AgentControllerMcp__CompleteTask，"完成任务"不必涵盖所有情况',
          '   - 额外章节（输入约束 / 数据流 等）：按需添加建议增加`数据策略`章节指导Agent如何应为共享存储的不同情况',
          '7. `agent_prompt`不要出现Flow/Agent/共享存储相关的词，将其视作仅有输入输出的独立节点',
        ].join('\n'),
        outputs: [
          {
            output_name: '设计完毕',
            next_agent: '3',
          },
        ],
        id: '2',
      },
      {
        node_type: 'agent',
        agent_name: '审查工作流',
        model: 'glm-5.1',
        effort: 'max',
        work_mode: 'silent_task',
        allowed_read_values_keys: ['generatedFlow', 'steps', 'requirement', 'changeList'],
        deny_tools: ['Bash(git commit)', 'Bash(git merge)', 'Bash(git push)', 'Edit'],
        isolation_mode: true,
        agent_prompt: [
          '### 你的职责',
          '审查Flow是否符合需求以及可能存在的问题',
          '### 执行步骤',
          '#### 1.获取JSON Schema',
          '调用GetFlowJSONSchema',
          '#### 2.初步验证',
          '判断Flow是否满足用户需求',
          '注意，只验证逻辑的正确性，确保正确使用Flow时不会出错，确保shareValues能被正确使用，忽略边界情况和安全性问题',
          '如果不满足，调用mcp__AgentControllerMcp__mcp__AgentControllerMcp__CompleteTask，选择分支"验证失败"，输出你的意见',
          '否则，进入下一步',
          '#### 3.深度审查',
          '将Flow绘制为 mermaid 流程图，并将其中每个Agent的的职责、输入输出、连边关系分别展示出来，说明节点如何使用和修改shareValues',
          '若 `changeList` 非空，简述上一轮累计的变更项',
          '#### 4.完成任务',
          '调用mcp__AgentControllerMcp__mcp__AgentControllerMcp__CompleteTask，选择分支"验证通过"，content为"审查通过"',
          '### 数据策略',
          '如果你从输入和generatedFlow中能获取与Flow Schema语义相近的JSON字符串，将其视作你本次分析的Flow',
          'changeList代表着Flow过往的变更记录，作为参考',
          'requirement是用户需求，steps是对其的拆分，是最直接有效的参考一般情况下每个step都应当映射为一个Agent，但允许根据语义的拆分和聚合',
        ].join('\n'),
        outputs: [
          {
            output_name: '验证失败',
            next_agent: '2',
          },
          {
            output_name: '验证通过',
            require_confirm: true,
          },
        ],
        id: '3',
      },
    ],
    shareValuesKeys: [
      { key: 'requirement', desc: '用户原始需求摘要' },
      { key: 'steps', desc: '需求拆分得到的步骤列表' },
      { key: 'generatedFlow', desc: '当前轮次生成的 Flow JSON' },
      { key: 'changeList', desc: '工作流的累计变更记录' },
    ],
  },
]
